# -*- coding:utf-8 -*-
import numpy as np
import pandas as pd
from pycoingecko import CoinGeckoAPI
import pickle as pkl
from datetime import *
from CoinStatistics.utility import download_monthly_klines
import zipfile
import os
import time

binance_symbol = "HNT,BOND,WOO,ZEN,GRS,AAVE,LINKDOWN,DCR,UMA,FORTH,RVN,CVX,STEEM,RNDR,KSM,BAR,XTZUP,FTT,ERD,CKB,FXS,MCO,SUB,JUV,BNX,GHST,WING,CHESS,LTC,TRXDOWN,CHAT,XRPBULL,BCHUP,SNM,DGB,STPT,EGLD,TWT,SAND,XMR,BICO,TROY,REN,BAND,ACH,MBOX,GLMR,IOST,DAI,CDT,ATM,SOL,USDC,ARN,BRD,ETHBULL,FILDOWN,RSR,ADA,BURGER,YGG,TKO,SKY,BNBBEAR,OGN,CLOAK,FRONT,PERL,CLV,LOKA,RAY,WAN,EASY,AST,COTI,LINK,PAXG,GVT,KNC,DENT,LUN,NPXS,DOGE,OOKI,HIVE,XLMDOWN,MBL,GXS,FIS,NULS,TLM,ENJ,STRAT,PERP,PUNDIX,C98,FLOW,NAV,XTZDOWN,NAS,RDN,XEC,DYDX,ZRX,VEN,NEO,SRM,ANT,TORN,QNT,ICN,USDP,EOS,UTK,IDEX,GAS,BTT,REEF,ETH,LTO,JST,ALPHA,LRC,EOSUP,RCN,ARPA,ATA,BTTC,HOT,MATIC,FIO,THETA,MDX,DOT,COMP,KEEP,ENG,ASR,UNIDOWN,GALA,ELF,STMX,XRPUP,LINKUP,SNX,SANTOS,DF,TNB,KEY,VIBE,BUSD,DASH,RLC,SXP,NXS,POA,SFP,SPELL,ETHBEAR,BCHDOWN,BAT,BAKE,OM,ROSE,TRXUP,CELO,XVS,KP3R,ETHDOWN,VTHO,MDA,VET,BCHSV,ICP,NU,ACA,AUTO,AION,SNGLS,UST,FARM,BULL,QKC,HARD,AUD,USDSB,BCH,EOSBEAR,WRX,TRX,FIL,NBS,EZ,DODO,OST,REP,AMP,LUNA,LTCDOWN,FOR,CAKE,VITE,MKR,WIN,LOOM,STRAX,SUPER,MASK,LIT,EOSDOWN,MITH,TCT,BEAM,AKRO,ADX,LSK,MANA,GNO,FUN,WAVES,MOVR,SALT,TRB,POLS,UNIUP,ICX,ATOM,GTO,TVK,CHR,VOXEL,WBTC,YOYO,STORJ,EUR,SKL,APPC,AGI,ALPACA,RENBTC,SNT,GLM,MINA,AUDIO,STX,CTK,MTL,GO,NMR,LEND,PYR,BADGER,QUICK,PHX,NKN,GBP,ALPINE,FIRO,BAL,QSP,SUN,VIDT,ERN,FLM,XVG,STORM,DOTUP,AAVEDOWN,ONT,ARDR,RARE,REQ,NEBL,ALGO,BOT,PROM,DEXE,QTUM,HBAR,DOCK,CFX,ALCX,SHIB,ANY,SYS,WTC,CTXC,KLAY,OXT,CELR,BTCUP,DOTDOWN,XEM,SSV,BETA,CVP,1INCH,EOSBULL,FIDA,SUSHI,SXPDOWN,FUEL,ADADOWN,RIF,ENS,WAXP,DEGO,IOTX,BCD,PEOPLE,VGX,ANKR,UNFI,BTC,DNT,SUSHIDOWN,API3,HIGH,1INCHUP,HSR,DIA,OG,1INCHDOWN,AVA,BTCB,INS,AMB,SUSD,FTM,POND,OCEAN,BCPT,SUSHIUP,PNT,ANC,NANO,ONE,POWR,TOMO,BNT,DAR,YFII,IMX,IRIS,BEL,GRT,SC,ZIL,PLA,OAX,YFI,LPT,MLN,EDO,WINGS,AE,XNO,MFT,XLM,PPT,ACM,BTCDOWN,SLP,BTCST,HC,XTZ,AGLD,LTCUP,LAZIO,RAD,BCC,SCRT,PHA,BNB,FLUX,RUNE,EVX,BTG,DREP,XRPBEAR,TRIG,XRPDOWN,FILUP,WPR,PHB,OMG,GTC,DUSK,NEAR,IOTA,RAMP,SXPUP,PIVX,COS,INJ,BKRW,TNT,XRP,AVAX,EPS,MOD,QI,CND,QLC,KMD,TRU,GNT,JOE,RPX,ALICE,COCOS,NCASH,BLZ,USDS,XLMUP,CRV,TRIBE,BNBDOWN,ZEC,BTS,POE,XZC,CTSI,ILV,RGT,AERGO,AUCTION,UNI,LINA,ARK,FET,CHZ,POLY,AAVEUP,AGIX,YFIDOWN,BQX,MC,ETC,MTH,WNXM,BNBUP,BEAR,BCHABC,BNBBULL,ETHUP,TUSD,CVC,ADAUP,BCN,MIR,VIA,CITY,PORTO,KAVA,AXS,DLT,CMT,AR,WABI,PSG,TFUEL,VIB,JASMY,ORN,DGD,PAX,ONG,DATA,YFIUP,MDT,BZRX"
binance_symbol_list = binance_symbol.split(",")
require_binance_file_names = set()
require_coingecko_file_names = set()

download_flag = False
zip_flag = False
concat_flag = False
coin_gecko_flag = False
binance_price_flag = True

if __name__ == '__main__':

    # train/validation/test 要根据时间点分，否则会有leakage
    df = pd.read_csv("neg_binance_required_file_name.txt", sep="\t", names=["symbol_date", "market_cap_usd", "market_cap_btc", "price_usd", "price_btc",
                                                                            "volume_usd", "volume_btc", "twitter_follower", "reddit_subscriber", "alexa_rank"])

